# Generated by Django 5.1.2 on 2024-11-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo_c', models.FileField(blank=True, null=True, upload_to='archivosC/')),
                ('archivo_html', models.FileField(blank=True, null=True, upload_to='archivocHTML/')),
            ],
            options={
                'db_table': 'archivos',
            },
        ),
    ]
